// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jelltafwhjjfijqjryri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplbGx0YWZ3aGpqZmlqcWpyeXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDU0NzUsImV4cCI6MjA2NTk4MTQ3NX0.lZsvZ9qBg6Bc4lKz_HKwMl8HmLg2sGCLClNyJ9XXRl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);